# Basic data exploration

In [1]:
import pandas as pd
import numpy as np

In [2]:
d=pd.read_csv("may-october(5 min).csv")
d

,Time,InverterSN,Data LoggerSN,Alert Details,Alert Code,DC Voltage PV1(V),DC Voltage PV2(V),DC Voltage PV3(V),DC Voltage PV4(V),DC Current1(A),...,AC Output Frequency R(Hz),Generation of Last Month (Active)(kWh),Daily Generation (Active)(kWh),Total Generation (Active)(kWh),Power Grid Total Apparent Power(VA),Grid Power Factor,Inverter Temperature(â„ƒ),Inverter Status,Generation Yesterday(kWh),System Time
0,2022/05/02 05:55,110470185160082,706238511,NaN,NaN,92.2,165.4,94.8,86.5,0.1,...,50.00,3164,0.0,117029.0,80,1.0,32.9,1022,126.9,22-5-2 6:16:1
1,2022/05/02 06:00,110470185160082,706238511,NaN,NaN,200.1,236.2,200.1,536.4,0.1,...,50.10,3164,0.0,117029.0,20,1.0,34.1,1022,126.9,22-5-2 6:21:39
2,2022/05/02 06:05,110470185160082,706238511,NaN,NaN,207.8,344.2,216.1,536.4,0.1,...,50.11,3164,0.0,117029.0,30,1.0,34.4,1022,126.9,22-5-2 6:26:12
3,2022/05/02 06:12,110470185160082,706238511,NaN,NaN,228.1,596.1,228.0,536.3,0.2,...,50.01,3164,0.0,117029.0,190,1.0,34.9,1022,126.9,22-5-2 6:33:15
4,2022/05/02 06:17,110470185160082,706238511,NaN,NaN,240.1,608.1,240.1,536.6,0.2,...,50.06,3164,0.0,117029.0,160,1.0,35.3,1022,126.9,22-5-2 6:38:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23272,2022/10/09 17:53,110470185160082,706238511,NaN,NaN,200.0,546.6,200.0,200.0,0.1,...,49.99,2835,82.4,133462.0,80,1.0,37.8,1022,131.9,22-10-9 18:22:15
23273,2022/10/09 17:58,110470185160082,706238511,NaN,NaN,199.9,200.1,476.1,509.6,0.1,...,50.03,2835,82.4,133462.0,70,1.0,37.6,1022,131.9,22-10-9 18:26:40
23274,2022/10/09 18:03,110470185160082,706238511,NaN,NaN,457.3,200.0,476.3,509.6,0.1,...,50.06,2835,82.4,133462.0,140,1.0,37.4,1022,131.9,22-10-9 18:32:14
23275,2022/10/09 18:09,110470185160082,706238511,NaN,NaN,437.6,420.4,382.1,389.7,0.1,...,49.96,2835,82.4,133462.0,140,1.0,37.1,1022,131.9,22-10-9 18:37:44
23276,2022/10/09 18:14,110470185160082,706238511,NaN,NaN,193.3,258.8,184.9,188.8,0.1,...,50.03,2835,82.4,133462.0,130,1.0,36.8,1022,131.9,22-10-9 18:43:15

In [3]:
d.columns

Index(['Time', 'InverterSN', 'Data LoggerSN', 'Alert Details', 'Alert Code',
       'DC Voltage PV1(V)', 'DC Voltage PV2(V)', 'DC Voltage PV3(V)',
       'DC Voltage PV4(V)', 'DC Current1(A)', 'DC Current2(A)',
       'DC Current3(A)', 'DC Current4(A)', 'Total DC Input Power(W)',
       'AC Voltage R/U/A(V)', 'AC Voltage S/V/B(V)', 'AC Voltage T/W/C(V)',
       'AC Current R/U/A(A)', 'AC Current S/V/B(A)', 'AC Current T/W/C(A)',
       'AC Output Total Power (Active)(W)', 'AC Output Frequency R(Hz)',
       'Generation of Last Month (Active)(kWh)',
       'Daily Generation (Active)(kWh)', 'Total Generation (Active)(kWh)',
       'Power Grid Total Apparent Power(VA)', 'Grid Power Factor',
       'Inverter Temperature(â„ƒ)', 'Inverter Status',
       'Generation Yesterday(kWh)', 'System Time'],
      dtype='object')

In [4]:
d['InverterSN'].unique

<bound method Series.unique of 0        110470185160082
1        110470185160082
2        110470185160082
3        110470185160082
4        110470185160082
              ...
23272    110470185160082
23273    110470185160082
23274    110470185160082
23275    110470185160082
23276    110470185160082
Name: InverterSN, Length: 23277, dtype: int64>

In [5]:
d['InverterSN'].value_counts()

110470185160082    23277
Name: InverterSN, dtype: int64

In [6]:
d['Data LoggerSN'].unique

<bound method Series.unique of 0        706238511
1        706238511
2        706238511
3        706238511
4        706238511
           ...
23272    706238511
23273    706238511
23274    706238511
23275    706238511
23276    706238511
Name: Data LoggerSN, Length: 23277, dtype: int64>

In [7]:
d['Data LoggerSN'].value_counts()

706238511    23277
Name: Data LoggerSN, dtype: int64

In [8]:
d['Inverter Status'].unique

<bound method Series.unique of 0        1022
1        1022
2        1022
3        1022
4        1022
         ...
23272    1022
23273    1022
23274    1022
23275    1022
23276    1022
Name: Inverter Status, Length: 23277, dtype: object>

In [9]:
d['Inverter Status'].value_counts()

1022       22835
1025         415
Standby       27
Name: Inverter Status, dtype: int64

In [10]:
d.shape

(23277, 31)

In [11]:
d.dtypes

Time                                       object
InverterSN                                  int64
Data LoggerSN                               int64
Alert Details                              object
Alert Code                                 object
DC Voltage PV1(V)                         float64
DC Voltage PV2(V)                         float64
DC Voltage PV3(V)                         float64
DC Voltage PV4(V)                         float64
DC Current1(A)                            float64
DC Current2(A)                            float64
DC Current3(A)                            float64
DC Current4(A)                            float64
Total DC Input Power(W)                     int64
AC Voltage R/U/A(V)                       float64
AC Voltage S/V/B(V)                       float64
AC Voltage T/W/C(V)                       float64
AC Current R/U/A(A)                       float64
AC Current S/V/B(A)                       float64
AC Current T/W/C(A)                       float64
AC Output Total Power (Active)(W)           int64
AC Output Frequency R(Hz)                 float64
Generation of Last Month (Active)(kWh)      int64
Daily Generation (Active)(kWh)            float64
Total Generation (Active)(kWh)            float64
Power Grid Total Apparent Power(VA)         int64
Grid Power Factor                         float64
Inverter Temperature(â„ƒ)                   float64
Inverter Status                            object
Generation Yesterday(kWh)                 float64
System Time                                object
dtype: object

In [12]:
x=d.columns
l=[]
for i in range(1,len(x)-1):
    l.append(d[x[i]].value_counts())
for i in l:
    print(i)

110470185160082    23277
Name: InverterSN, dtype: int64
706238511    23277
Name: Data LoggerSN, dtype: int64
N    329
G     86
Name: Alert Details, dtype: int64
1015H    329
1012H     78
1010H      5
1011H      3
Name: Alert Code, dtype: int64
200.1    142
632.1    119
200.0    119
640.1    117
624.0    116
        ...
305.5      1
732.8      1
135.4      1
285.4      1
193.3      1
Name: DC Voltage PV1(V), Length: 2456, dtype: int64
200.1    116
200.0    101
616.1     86
612.1     82
643.9     82
        ...
549.3      1
394.3      1
163.6      1
207.4      1
258.8      1
Name: DC Voltage PV2(V), Length: 2355, dtype: int64
200.1    154
200.0    148
620.0    118
636.1    115
632.1    112
        ...
454.9      1
505.7      1
506.0      1
506.3      1
184.9      1
Name: DC Voltage PV3(V), Length: 2582, dtype: int64
200.0    173
671.9    130
672.1    129
200.1    129
672.0    127
        ...
146.2      1
243.1      1
405.5      1
504.7      1
188.8      1
Name: DC Voltage PV4(V), Length: 2589, dtype: int64
0.1     1876
0.2      912
0.3      765
0.4      629
0.7      580
        ...
10.0       2
10.5       2
10.3       1
10.9       1
11.6       1
Name: DC Current1(A), Length: 107, dtype: int64
0.1     1190
0.2      632
0.3      505
0.0      428
0.4      411
        ...
17.7      15
17.3      13
17.9      10
18.1       6
18.4       1
Name: DC Current2(A), Length: 183, dtype: int64
0.1     1938
0.2      940
0.3      754
0.4      631
0.5      617
        ...
11.3       1
11.1       1
11.2       1
10.1       1
10.2       1
Name: DC Current3(A), Length: 110, dtype: int64
0.1     2032
0.2      836
0.3      810
0.4      683
0.5      590
        ...
11.1       1
10.3       1
10.9       1
11.4       1
10.7       1
Name: DC Current4(A), Length: 109, dtype: int64
0        428
80        67
169       34
166       33
139       32
        ...
11159      1
6328       1
16150      1
17382      1
1764       1
Name: Total DC Input Power(W), Length: 13181, dtype: int64
234.6    403
235.8    402
235.5    399
236.2    380
233.9    379
        ...
200.3      1
201.2      1
202.5      1
196.5      1
268.2      1
Name: AC Voltage R/U/A(V), Length: 218, dtype: int64
237.7    411
237.4    400
237.1    397
236.2    396
236.5    394
        ...
203.1      1
204.1      1
202.2      1
203.5      1
268.5      1
Name: AC Voltage S/V/B(V), Length: 209, dtype: int64
239.0    402
235.8    400
237.1    396
238.7    392
236.8    389
        ...
199.0      1
206.6      1
201.6      1
186.9      1
200.0      1
Name: AC Voltage T/W/C(V), Length: 210, dtype: int64
0.0     1245
0.1      500
0.2      272
0.4      256
1.7      231
        ...
37.1       1
40.6       1
42.5       1
38.0       1
39.3       1
Name: AC Current R/U/A(A), Length: 403, dtype: int64
0.0     1245
0.1      500
0.2      272
0.4      256
1.5      253
        ...
36.0       1
38.4       1
39.9       1
40.1       1
39.7       1
Name: AC Current S/V/B(A), Length: 399, dtype: int64
0.0     1245
0.1      500
0.2      272
0.4      256
1.9      221
        ...
39.1       1
40.0       1
37.7       1
39.4       1
41.8       1
Name: AC Current T/W/C(A), Length: 399, dtype: int64
20       1443
0         428
160        66
210        65
100        62
         ...
26100       1
25250       1
15710       1
26250       1
24540       1
Name: AC Output Total Power (Active)(W), Length: 2617, dtype: int64
49.99    3466
50.00    2040
50.03    1991
50.01    1752
50.06    1570
         ...
49.53       1
49.50       1
51.42       1
51.51       1
51.22       1
Name: AC Output Frequency R(Hz), Length: 113, dtype: int64
2544    4672
3164    4532
3833    4528
3225    4294
3374    4268
2835     983
Name: Generation of Last Month (Active)(kWh), dtype: int64
0.0      849
0.1      376
0.2      206
0.3      165
0.4      146
        ...
153.3      1
153.4      1
149.4      1
153.6      1
142.2      1
Name: Daily Generation (Active)(kWh), Length: 1535, dtype: int64
126395.0    54
133206.0    54
127161.0    43
124934.0    42
126091.0    42
            ..
119746.0     1
119748.0     1
119750.0     1
119752.0     1
127416.0     1
Name: Total Generation (Active)(kWh), Length: 12584, dtype: int64
0        507
50       232
100      204
80       151
40       148
        ...
21810      1
27490      1
25750      1
28000      1
24860      1
Name: Power Grid Total Apparent Power(VA), Length: 2607, dtype: int64
1.0    23277
Name: Grid Power Factor, dtype: int64
41.0    135
35.3    116
42.0    109
40.0    105
44.0    100
       ...
72.6      1
72.5      1
72.7      1
72.1      1
25.1      1
Name: Inverter Temperature(â„ƒ), Length: 489, dtype: int64
1022       22835
1025         415
Standby       27
Name: Inverter Status, dtype: int64
118.1    311
118.9    309
29.8     292
119.9    291
79.3     287
        ...
124.7    108
111.9    105
93.3      82
78.1      19
0.0        5
Name: Generation Yesterday(kWh), Length: 153, dtype: int64

Conclusion:Alert details, Alert code, Grid power factor, Inverter status attributes doesnt have much unique values

In [13]:
d=d[['Time', 'DC Voltage PV1(V)', 'DC Voltage PV2(V)', 'DC Voltage PV3(V)',
       'DC Voltage PV4(V)', 'DC Current1(A)', 'DC Current2(A)',
       'DC Current3(A)', 'DC Current4(A)', 'Total DC Input Power(W)',
       'AC Voltage R/U/A(V)', 'AC Voltage S/V/B(V)', 'AC Voltage T/W/C(V)',
       'AC Current R/U/A(A)', 'AC Current S/V/B(A)', 'AC Current T/W/C(A)',
       'AC Output Total Power (Active)(W)', 'AC Output Frequency R(Hz)',
       'Generation of Last Month (Active)(kWh)',
       'Daily Generation (Active)(kWh)', 'Total Generation (Active)(kWh)',
       'Power Grid Total Apparent Power(VA)',
       'Inverter Temperature(â„ƒ)',
       'Generation Yesterday(kWh)']]

In [14]:
d.head(10)

,Time,DC Voltage PV1(V),DC Voltage PV2(V),DC Voltage PV3(V),DC Voltage PV4(V),DC Current1(A),DC Current2(A),DC Current3(A),DC Current4(A),Total DC Input Power(W),...,AC Current S/V/B(A),AC Current T/W/C(A),AC Output Total Power (Active)(W),AC Output Frequency R(Hz),Generation of Last Month (Active)(kWh),Daily Generation (Active)(kWh),Total Generation (Active)(kWh),Power Grid Total Apparent Power(VA),Inverter Temperature(â„ƒ),Generation Yesterday(kWh)
0,2022/05/02 05:55,92.2,165.4,94.8,86.5,0.1,0.1,0.1,0.1,43,...,0.0,0.0,20,50.00,3164,0.0,117029.0,80,32.9,126.9
1,2022/05/02 06:00,200.1,236.2,200.1,536.4,0.1,0.2,0.1,0.1,140,...,0.1,0.1,30,50.10,3164,0.0,117029.0,20,34.1,126.9
2,2022/05/02 06:05,207.8,344.2,216.1,536.4,0.1,0.2,0.1,0.1,164,...,0.2,0.2,40,50.11,3164,0.0,117029.0,30,34.4,126.9
3,2022/05/02 06:12,228.1,596.1,228.0,536.3,0.2,0.3,0.2,0.2,377,...,0.4,0.4,200,50.01,3164,0.0,117029.0,190,34.9,126.9
4,2022/05/02 06:17,240.1,608.1,240.1,536.6,0.2,0.3,0.2,0.2,385,...,0.5,0.5,160,50.06,3164,0.0,117029.0,160,35.3,126.9
5,2022/05/02 06:22,268.1,603.6,267.8,252.1,0.2,0.4,0.2,0.2,399,...,0.5,0.5,220,50.05,3164,0.1,117029.0,240,35.4,126.9
6,2022/05/02 06:27,548.0,611.8,523.9,452.3,0.3,0.5,0.3,0.3,763,...,0.9,0.9,500,50.03,3164,0.1,117029.0,480,35.7,126.9
7,2022/05/02 06:33,616.0,624.0,632.1,664.1,0.3,0.6,0.3,0.3,948,...,1.4,1.3,740,49.99,3164,0.1,117029.0,710,36.1,126.9
8,2022/05/02 06:38,628.1,628.0,628.3,660.0,0.4,0.8,0.4,0.4,1268,...,1.7,1.7,1080,50.06,3164,0.2,117029.0,1080,36.5,126.9
9,2022/05/02 06:43,627.8,635.3,628.1,667.7,0.6,1.0,0.6,0.5,1722,...,2.4,2.3,1540,50.01,3164,0.3,117029.0,1530,36.8,126.9

In [15]:
d.isna().sum()

Time                                      0
DC Voltage PV1(V)                         0
DC Voltage PV2(V)                         0
DC Voltage PV3(V)                         0
DC Voltage PV4(V)                         0
DC Current1(A)                            0
DC Current2(A)                            0
DC Current3(A)                            0
DC Current4(A)                            0
Total DC Input Power(W)                   0
AC Voltage R/U/A(V)                       0
AC Voltage S/V/B(V)                       0
AC Voltage T/W/C(V)                       0
AC Current R/U/A(A)                       0
AC Current S/V/B(A)                       0
AC Current T/W/C(A)                       0
AC Output Total Power (Active)(W)         0
AC Output Frequency R(Hz)                 0
Generation of Last Month (Active)(kWh)    0
Daily Generation (Active)(kWh)            0
Total Generation (Active)(kWh)            0
Power Grid Total Apparent Power(VA)       0
Inverter Temperature(â„ƒ)                   0
Generation Yesterday(kWh)                 0
dtype: int64

# Converting to datetime

In [16]:
d.dtypes

Time                                       object
DC Voltage PV1(V)                         float64
DC Voltage PV2(V)                         float64
DC Voltage PV3(V)                         float64
DC Voltage PV4(V)                         float64
DC Current1(A)                            float64
DC Current2(A)                            float64
DC Current3(A)                            float64
DC Current4(A)                            float64
Total DC Input Power(W)                     int64
AC Voltage R/U/A(V)                       float64
AC Voltage S/V/B(V)                       float64
AC Voltage T/W/C(V)                       float64
AC Current R/U/A(A)                       float64
AC Current S/V/B(A)                       float64
AC Current T/W/C(A)                       float64
AC Output Total Power (Active)(W)           int64
AC Output Frequency R(Hz)                 float64
Generation of Last Month (Active)(kWh)      int64
Daily Generation (Active)(kWh)            float64
Total Generation (Active)(kWh)            float64
Power Grid Total Apparent Power(VA)         int64
Inverter Temperature(â„ƒ)                   float64
Generation Yesterday(kWh)                 float64
dtype: object

In [17]:
d.loc[:,'Time'] = d['Time'].astype('string')#converted time to string
d.dtypes

c:\Users\Ananya Peruru\anaconda3\lib\site-packages\pandas\core\indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

Time                                       string
DC Voltage PV1(V)                         float64
DC Voltage PV2(V)                         float64
DC Voltage PV3(V)                         float64
DC Voltage PV4(V)                         float64
DC Current1(A)                            float64
DC Current2(A)                            float64
DC Current3(A)                            float64
DC Current4(A)                            float64
Total DC Input Power(W)                     int64
AC Voltage R/U/A(V)                       float64
AC Voltage S/V/B(V)                       float64
AC Voltage T/W/C(V)                       float64
AC Current R/U/A(A)                       float64
AC Current S/V/B(A)                       float64
AC Current T/W/C(A)                       float64
AC Output Total Power (Active)(W)           int64
AC Output Frequency R(Hz)                 float64
Generation of Last Month (Active)(kWh)      int64
Daily Generation (Active)(kWh)            float64
Total Generation (Active)(kWh)            float64
Power Grid Total Apparent Power(VA)         int64
Inverter Temperature(â„ƒ)                   float64
Generation Yesterday(kWh)                 float64
dtype: object

In [18]:
d['Time']= pd.to_datetime(d['Time'])
d.dtypes

C:\Users\ANANYA~1\AppData\Local\Temp/ipykernel_18568/2473265570.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d['Time']= pd.to_datetime(d['Time'])

Time                                      datetime64[ns]
DC Voltage PV1(V)                                float64
DC Voltage PV2(V)                                float64
DC Voltage PV3(V)                                float64
DC Voltage PV4(V)                                float64
DC Current1(A)                                   float64
DC Current2(A)                                   float64
DC Current3(A)                                   float64
DC Current4(A)                                   float64
Total DC Input Power(W)                            int64
AC Voltage R/U/A(V)                              float64
AC Voltage S/V/B(V)                              float64
AC Voltage T/W/C(V)                              float64
AC Current R/U/A(A)                              float64
AC Current S/V/B(A)                              float64
AC Current T/W/C(A)                              float64
AC Output Total Power (Active)(W)                  int64
AC Output Frequency R(Hz)                        float64
Generation of Last Month (Active)(kWh)             int64
Daily Generation (Active)(kWh)                   float64
Total Generation (Active)(kWh)                   float64
Power Grid Total Apparent Power(VA)                int64
Inverter Temperature(â„ƒ)                          float64
Generation Yesterday(kWh)                        float64
dtype: object

In [50]:
d.head()
d.to_csv('file_name.csv')

In [20]:
from datetime import date
dates=d
s=(dates['Time'].apply(lambda x: x.date()).value_counts() >= 80) 
s

2022-06-07     True
2022-06-14     True
2022-06-08     True
2022-08-03     True
2022-06-05     True
              ...
2022-05-27     True
2022-09-29     True
2022-06-29     True
2022-10-05    False
2022-10-06    False
Name: Time, Length: 159, dtype: bool

In [47]:
d2=pd.read_csv("new_file.csv")
d2

FileNotFoundError: [Errno 2] No such file or directory: 'new_file.csv'

In [48]:
x=d2.columns
l=[]
for i in range(1,len(x)-1):
    l.append(d2[x[i]].value_counts())
for i in l:
    print(i)

NameError: name 'd2' is not defined

In [33]:
d2=d2[['Time', 'DC Voltage PV1(V)', 'DC Voltage PV2(V)', 'DC Voltage PV3(V)',
       'DC Voltage PV4(V)', 'DC Current1(A)', 'DC Current2(A)',
       'DC Current3(A)', 'DC Current4(A)', 'Total DC Input Power(W)',
       'AC Voltage R/U/A(V)', 'AC Voltage S/V/B(V)', 'AC Voltage T/W/C(V)',
       'AC Current R/U/A(A)', 'AC Current S/V/B(A)', 'AC Current T/W/C(A)',
       'AC Output Total Power (Active)(W)', 'AC Output Frequency R(Hz)',
       'Generation of Last Month (Active)(kWh)',
       'Daily Generation (Active)(kWh)', 'Total Generation (Active)(kWh)',
       'Power Grid Total Apparent Power(VA)',
       'Inverter Temperature(â„ƒ)',
       'Generation Yesterday(kWh)']]

NameError: name 'd2' is not defined

In [34]:
d.head(10)

,Time,DC Voltage PV1(V),DC Voltage PV2(V),DC Voltage PV3(V),DC Voltage PV4(V),DC Current1(A),DC Current2(A),DC Current3(A),DC Current4(A),Total DC Input Power(W),...,AC Current S/V/B(A),AC Current T/W/C(A),AC Output Total Power (Active)(W),AC Output Frequency R(Hz),Generation of Last Month (Active)(kWh),Daily Generation (Active)(kWh),Total Generation (Active)(kWh),Power Grid Total Apparent Power(VA),Inverter Temperature(â„ƒ),Generation Yesterday(kWh)
0,2022-05-02 05:55:00,92.2,165.4,94.8,86.5,0.1,0.1,0.1,0.1,43,...,0.0,0.0,20,50.00,3164,0.0,117029.0,80,32.9,126.9
1,2022-05-02 06:00:00,200.1,236.2,200.1,536.4,0.1,0.2,0.1,0.1,140,...,0.1,0.1,30,50.10,3164,0.0,117029.0,20,34.1,126.9
2,2022-05-02 06:05:00,207.8,344.2,216.1,536.4,0.1,0.2,0.1,0.1,164,...,0.2,0.2,40,50.11,3164,0.0,117029.0,30,34.4,126.9
3,2022-05-02 06:12:00,228.1,596.1,228.0,536.3,0.2,0.3,0.2,0.2,377,...,0.4,0.4,200,50.01,3164,0.0,117029.0,190,34.9,126.9
4,2022-05-02 06:17:00,240.1,608.1,240.1,536.6,0.2,0.3,0.2,0.2,385,...,0.5,0.5,160,50.06,3164,0.0,117029.0,160,35.3,126.9
5,2022-05-02 06:22:00,268.1,603.6,267.8,252.1,0.2,0.4,0.2,0.2,399,...,0.5,0.5,220,50.05,3164,0.1,117029.0,240,35.4,126.9
6,2022-05-02 06:27:00,548.0,611.8,523.9,452.3,0.3,0.5,0.3,0.3,763,...,0.9,0.9,500,50.03,3164,0.1,117029.0,480,35.7,126.9
7,2022-05-02 06:33:00,616.0,624.0,632.1,664.1,0.3,0.6,0.3,0.3,948,...,1.4,1.3,740,49.99,3164,0.1,117029.0,710,36.1,126.9
8,2022-05-02 06:38:00,628.1,628.0,628.3,660.0,0.4,0.8,0.4,0.4,1268,...,1.7,1.7,1080,50.06,3164,0.2,117029.0,1080,36.5,126.9
9,2022-05-02 06:43:00,627.8,635.3,628.1,667.7,0.6,1.0,0.6,0.5,1722,...,2.4,2.3,1540,50.01,3164,0.3,117029.0,1530,36.8,126.9

In [35]:
d2.isna().sum()

NameError: name 'd2' is not defined

In [23]:
d2.dtypes

NameError: name 'd2' is not defined

In [36]:
d2.loc[:,'Time'] = d2['Time'].astype('string')#converted time to string
d2.dtypes

NameError: name 'd2' is not defined

In [26]:
d2['Time']= pd.to_datetime(d2['Time'])
d2.dtypes

NameError: name 'd2' is not defined

In [37]:
from datetime import date
dates=d2
s=(dates['Time'].apply(lambda x: x.date()).value_counts() >= 80) 
s

NameError: name 'd2' is not defined

In [ ]:
#the final dataset is d2. Use d2 from now on.

In [28]:
import matplotlib.pyplot as plt

In [39]:
s.plot()
plt.show()

TypeError: no numeric data to plot

In [40]:
d.tail(10)

,Time,DC Voltage PV1(V),DC Voltage PV2(V),DC Voltage PV3(V),DC Voltage PV4(V),DC Current1(A),DC Current2(A),DC Current3(A),DC Current4(A),Total DC Input Power(W),...,AC Current S/V/B(A),AC Current T/W/C(A),AC Output Total Power (Active)(W),AC Output Frequency R(Hz),Generation of Last Month (Active)(kWh),Daily Generation (Active)(kWh),Total Generation (Active)(kWh),Power Grid Total Apparent Power(VA),Inverter Temperature(â„ƒ),Generation Yesterday(kWh)
23267,2022-10-09 17:27:00,617.5,619.0,621.9,670.4,0.4,0.7,0.3,0.3,1067,...,1.6,1.5,970,50.01,2835,82.2,133462.0,800,39.2,131.9
23268,2022-10-09 17:32:00,613.1,606.6,625.5,658.1,0.3,0.6,0.3,0.3,932,...,1.5,1.4,730,50.08,2835,82.3,133462.0,720,38.7,131.9
23269,2022-10-09 17:37:00,644.9,599.1,609.8,658.3,0.2,0.5,0.2,0.2,682,...,0.8,0.8,430,49.95,2835,82.4,133462.0,450,38.4,131.9
23270,2022-10-09 17:43:00,621.2,590.9,593.7,650.9,0.1,0.3,0.1,0.1,363,...,0.5,0.5,250,49.94,2835,82.4,133462.0,240,38.2,131.9
23271,2022-10-09 17:48:00,576.9,591.0,233.6,274.3,0.1,0.2,0.1,0.1,226,...,0.2,0.2,30,50.05,2835,82.4,133462.0,10,38.0,131.9
23272,2022-10-09 17:53:00,200.0,546.6,200.0,200.0,0.1,0.1,0.1,0.1,114,...,0.1,0.1,20,49.99,2835,82.4,133462.0,80,37.8,131.9
23273,2022-10-09 17:58:00,199.9,200.1,476.1,509.6,0.1,0.1,0.1,0.1,138,...,0.0,0.0,20,50.03,2835,82.4,133462.0,70,37.6,131.9
23274,2022-10-09 18:03:00,457.3,200.0,476.3,509.6,0.1,0.1,0.1,0.1,164,...,0.0,0.0,20,50.06,2835,82.4,133462.0,140,37.4,131.9
23275,2022-10-09 18:09:00,437.6,420.4,382.1,389.7,0.1,0.1,0.1,0.1,162,...,0.0,0.0,20,49.96,2835,82.4,133462.0,140,37.1,131.9
23276,2022-10-09 18:14:00,193.3,258.8,184.9,188.8,0.1,0.1,0.1,0.1,82,...,0.0,0.0,20,50.03,2835,82.4,133462.0,130,36.8,131.9

# Converting to 1 HR intervals

In [41]:
d.set_index('Time',inplace= True)

In [42]:
df=d
df=df.resample("1H").mean()
df

,DC Voltage PV1(V),DC Voltage PV2(V),DC Voltage PV3(V),DC Voltage PV4(V),DC Current1(A),DC Current2(A),DC Current3(A),DC Current4(A),Total DC Input Power(W),AC Voltage R/U/A(V),...,AC Current S/V/B(A),AC Current T/W/C(A),AC Output Total Power (Active)(W),AC Output Frequency R(Hz),Generation of Last Month (Active)(kWh),Daily Generation (Active)(kWh),Total Generation (Active)(kWh),Power Grid Total Apparent Power(VA),Inverter Temperature(â„ƒ),Generation Yesterday(kWh)
Time,,,,,,,,,,,,,,,,,,,,,
2022-05-02 05:00:00,92.200000,165.400000,94.800000,86.500000,0.100000,0.100000,0.100000,0.100000,43.000000,236.800000,...,0.000000,0.000000,20.000000,50.000000,3164.0,0.000000,117029.000000,80.000000,32.900000,126.9
2022-05-02 06:00:00,455.016667,568.625000,455.058333,572.833333,0.416667,0.733333,0.408333,0.408333,1171.583333,235.258333,...,1.516667,1.516667,974.166667,50.042500,3164.0,0.241667,117029.250000,966.666667,36.025000,126.9
2022-05-02 07:00:00,637.527273,645.463636,608.336364,672.427273,1.654545,2.781818,1.590909,1.581818,4868.545455,234.718182,...,6.572727,6.545455,4662.727273,50.061818,3164.0,2.954545,117031.909091,4650.000000,41.400000,126.9
2022-05-02 08:00:00,625.583333,625.608333,621.641667,661.633333,3.300000,6.375000,3.308333,3.250000,10230.333333,236.733333,...,13.841667,13.866667,9886.666667,50.080000,3164.0,10.008333,117039.000000,9890.000000,48.441667,126.9
2022-05-02 09:00:00,604.027273,608.400000,606.981818,639.736364,4.763636,9.354545,4.754545,4.709091,14452.090909,233.936364,...,19.909091,19.745455,13979.090909,50.028182,3164.0,22.709091,117051.727273,13969.090909,56.872727,126.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-09 14:00:00,731.608333,729.033333,732.191667,767.866667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,2835.0,67.000000,133446.000000,0.000000,38.358333,131.9
2022-10-09 15:00:00,652.225000,658.508333,663.175000,693.491667,3.175000,5.908333,3.066667,3.066667,9512.666667,175.350000,...,11.633333,11.600000,9235.000000,33.358333,2835.0,70.283333,133449.416667,9236.666667,42.691667,131.9
2022-10-09 16:00:00,616.900000,634.436364,636.845455,673.309091,1.772727,3.418182,1.672727,1.690909,5404.000000,255.236364,...,6.745455,6.727273,5179.090909,49.995455,2835.0,79.563636,133458.909091,4351.818182,44.054545,131.9
2022-10-09 17:00:00,552.183333,577.425000,537.316667,581.341667,0.400000,0.741667,0.383333,0.366667,1171.833333,249.091667,...,1.525000,1.491667,1008.333333,50.011667,2835.0,82.141667,133461.666667,1000.000000,39.266667,131.9
2022-10-09 18:00:00,362.733333,293.066667,347.766667,362.700000,0.100000,0.100000,0.100000,0.100000,136.000000,244.833333,...,0.000000,0.000000,20.000000,50.016667,2835.0,82.400000,133462.000000,136.666667,37.100000,131.9

In [43]:
times=df.reset_index()
times

,Time,DC Voltage PV1(V),DC Voltage PV2(V),DC Voltage PV3(V),DC Voltage PV4(V),DC Current1(A),DC Current2(A),DC Current3(A),DC Current4(A),Total DC Input Power(W),...,AC Current S/V/B(A),AC Current T/W/C(A),AC Output Total Power (Active)(W),AC Output Frequency R(Hz),Generation of Last Month (Active)(kWh),Daily Generation (Active)(kWh),Total Generation (Active)(kWh),Power Grid Total Apparent Power(VA),Inverter Temperature(â„ƒ),Generation Yesterday(kWh)
0,2022-05-02 05:00:00,92.200000,165.400000,94.800000,86.500000,0.100000,0.100000,0.100000,0.100000,43.000000,...,0.000000,0.000000,20.000000,50.000000,3164.0,0.000000,117029.000000,80.000000,32.900000,126.9
1,2022-05-02 06:00:00,455.016667,568.625000,455.058333,572.833333,0.416667,0.733333,0.408333,0.408333,1171.583333,...,1.516667,1.516667,974.166667,50.042500,3164.0,0.241667,117029.250000,966.666667,36.025000,126.9
2,2022-05-02 07:00:00,637.527273,645.463636,608.336364,672.427273,1.654545,2.781818,1.590909,1.581818,4868.545455,...,6.572727,6.545455,4662.727273,50.061818,3164.0,2.954545,117031.909091,4650.000000,41.400000,126.9
3,2022-05-02 08:00:00,625.583333,625.608333,621.641667,661.633333,3.300000,6.375000,3.308333,3.250000,10230.333333,...,13.841667,13.866667,9886.666667,50.080000,3164.0,10.008333,117039.000000,9890.000000,48.441667,126.9
4,2022-05-02 09:00:00,604.027273,608.400000,606.981818,639.736364,4.763636,9.354545,4.754545,4.709091,14452.090909,...,19.909091,19.745455,13979.090909,50.028182,3164.0,22.709091,117051.727273,13969.090909,56.872727,126.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3849,2022-10-09 14:00:00,731.608333,729.033333,732.191667,767.866667,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,2835.0,67.000000,133446.000000,0.000000,38.358333,131.9
3850,2022-10-09 15:00:00,652.225000,658.508333,663.175000,693.491667,3.175000,5.908333,3.066667,3.066667,9512.666667,...,11.633333,11.600000,9235.000000,33.358333,2835.0,70.283333,133449.416667,9236.666667,42.691667,131.9
3851,2022-10-09 16:00:00,616.900000,634.436364,636.845455,673.309091,1.772727,3.418182,1.672727,1.690909,5404.000000,...,6.745455,6.727273,5179.090909,49.995455,2835.0,79.563636,133458.909091,4351.818182,44.054545,131.9
3852,2022-10-09 17:00:00,552.183333,577.425000,537.316667,581.341667,0.400000,0.741667,0.383333,0.366667,1171.833333,...,1.525000,1.491667,1008.333333,50.011667,2835.0,82.141667,133461.666667,1000.000000,39.266667,131.9
3853,2022-10-09 18:00:00,362.733333,293.066667,347.766667,362.700000,0.100000,0.100000,0.100000,0.100000,136.000000,...,0.000000,0.000000,20.000000,50.016667,2835.0,82.400000,133462.000000,136.666667,37.100000,131.9

In [ ]:
#from datetime import date,datetime,time

In [44]:
times['actual time']=times['Time'].apply(lambda x: x.time())
times[times['actual time']==time(6,00,00)]

NameError: name 'time' is not defined

In [45]:
w=pd.read_csv("weather_may_to_oct9.csv")
w

,name,datetime,temp,feelslike,dew,humidity,precip,precipprob,preciptype,snow,...,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,conditions,icon,stations
0,"17.4116, 78.3987",2022-05-02T00:00:00,88.7,89.4,62.6,41.86,0.00,0.0,NaN,0.0,...,1008.0,50.0,3.1,0.0,NaN,0.0,10.0,Partially cloudy,partly-cloudy-night,"43128599999,VOHS"
1,"17.4116, 78.3987",2022-05-02T01:00:00,86.0,87.1,63.5,47.07,0.00,0.0,NaN,0.0,...,1008.0,50.0,3.1,0.0,NaN,0.0,10.0,Partially cloudy,partly-cloudy-night,"43128599999,VOHS"
2,"17.4116, 78.3987",2022-05-02T02:00:00,87.4,90.1,66.5,50.00,0.00,0.0,NaN,0.0,...,1003.4,80.4,5.5,0.0,NaN,0.0,10.0,Partially cloudy,partly-cloudy-night,"43128599999,43128099999,VOHS"
3,"17.4116, 78.3987",2022-05-02T03:00:00,84.2,86.1,65.3,53.10,0.00,0.0,NaN,0.0,...,1007.0,50.0,3.1,0.0,NaN,0.0,60.0,Partially cloudy,partly-cloudy-night,"43128599999,VOHS"
4,"17.4116, 78.3987",2022-05-02T04:00:00,84.2,85.0,62.6,48.35,0.00,0.0,NaN,0.0,...,1007.0,50.0,3.1,0.0,NaN,0.0,60.0,Partially cloudy,partly-cloudy-night,"43128599999,VOHS"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3860,"17.4116, 78.3987",2021-10-09T20:00:00,74.1,74.1,72.1,93.25,2.52,100.0,rain,0.0,...,1010.9,93.8,2.2,0.0,NaN,0.0,NaN,"Rain, Overcast",rain,"VOHY,43128599999,43128099999,VOHS"
3861,"17.4116, 78.3987",2021-10-09T21:00:00,72.7,72.7,70.3,92.42,0.00,0.0,NaN,0.0,...,1013.0,98.4,1.9,0.0,NaN,0.0,NaN,Overcast,cloudy,"VOHY,43128599999,43128099999,VOHS"
3862,"17.4116, 78.3987",2021-10-09T22:00:00,78.8,78.8,75.2,88.76,0.00,0.0,NaN,0.0,...,1014.0,89.0,2.5,0.0,NaN,0.0,NaN,Partially cloudy,partly-cloudy-night,"43128599999,VOHS"
3863,"17.4116, 78.3987",2021-10-09T23:00:00,74.7,74.7,73.2,94.94,0.00,0.0,NaN,0.0,...,1009.2,89.8,2.5,0.0,NaN,0.0,NaN,Partially cloudy,partly-cloudy-night,"43128599999,43128099999,VOHS"
3864,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#combine weather and solar data